- name: Install dependencies
  ansible.builtin.package:
    name:
      - snmp
      - snmpd
      - snmp-mibs-downloader
    state: present
    update_cache: true

- name: Enable and start snmpd
  service:
    name: snmpd
    enabled: true
    state: started

- name: Remove all agentAddress lines (commented or not, any casing)
  ansible.builtin.replace:
    path: /etc/snmp/snmpd.conf
    regexp: '(?i)^#?\s*agentaddress.*'
    replace: ''
    backup: yes
  notify: restart snmpd

- name: Comment out the 'mibs :' line in /etc/snmp/snmp.conf if not already commented
  ansible.builtin.replace:
    path: /etc/snmp/snmp.conf
    regexp: '^mibs\s*:'
    replace: '#mibs :'
    backup: yes

- name: Ensure snmpd listens on all interfaces (IPv4 + loopback IPv6)
  lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: '^agentAddress'
    line: 'agentAddress udp:161,udp6:[::1]:161'
    create: yes
    backup: yes
  notify: "restart snmpd"

- name: Set system contact
  lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: '^sysContact'
    line: "sysContact {{ snmp_syscontact }}"
    insertafter: '^agentAddress.*'
  notify: "restart snmpd"

- name: Set system location
  lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: '^sysLocation'
    line: "sysLocation {{ snmp_syslocation }}"
    insertafter: '^sysContact.*'
  notify: "restart snmpd"

- name: Add createUser (will be consumed into /var/lib/snmp/snmpd.conf)
  lineinfile:
    path: /etc/snmp/snmpd.conf
    insertafter: EOF
    line: 'createUser {{ snmp_v3_user }} {{ snmp_v3_auth_protocol }} "{{ snmp_v3_auth_pass }}" {{ snmp_v3_priv_protocol }} "{{ snmp_v3_priv_pass }}"'
  notify: "restart snmpd"

- name: Ensure rouser has authPriv
  lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: '^rouser\s+{{ snmp_v3_user }}\s+priv'
    line: 'rouser {{ snmp_v3_user }} priv'
    insertafter: '^sysLocation.*'
  notify: "restart snmpd"
